export const routes = [
  // Static pages
  { loc: "/", priority: "1.00" },
  { loc: "/about-us", priority: "0.80" },
  { loc: "/our-services", priority: "0.80" },
  { loc: "/contact-us", priority: "0.80" },
  { loc: "/our-services/tourist-and-intercity-buses-in-udaipur", priority: "0.80" },
  { loc: "/our-services/corporate-staff-transportation-services-in-udaipur", priority: "0.80" },
  { loc: "/cargo-services", priority: "0.80" },
  { loc: "/our-services/car-rental-service-in-udaipur", priority: "0.80" },
  { loc: "/our-services/traveller-van-in-udaipur", priority: "0.80" },
  { loc: "/our-services/luxury-car-rental-in-udaipur", priority: "0.80" },
  { loc: "/our-fleets", priority: "0.80" },
  { loc: "/gallery", priority: "0.80" },
  { loc: "/events", priority: "0.80" },
  { loc: "/blog", priority: "0.80" },
  { loc: "/contact-us", priority: "0.80" },

  // Blog posts
  { loc: "/blog/udaipur-to-khatushyamji-bus-service", priority: "0.64" },
  { loc: "/blog/ac-bus-service-in-udaipur", priority: "0.64" },
  { loc: "/blog/best-bus-agency-in-udaipur", priority: "0.64" },
  { loc: "/blog/best-tour-operators-in-udaipur", priority: "0.64" },
  { loc: "/blog/bus-travel-agency-in-udaipur", priority: "0.64" },
  { loc: "/blog/corporate-bus-service-in-udaipur", priority: "0.64" },
  { loc: "/blog/luxury-bus-service-in-udaipur", priority: "0.64" },
  { loc: "/blog/taxi-service-in-udaipur-for-outstation", priority: "0.64" },
  { loc: "/blog/best-wedding-car-rental-services-in-udaipur", priority: "0.64" },
  { loc: "/blog/how-sleeper-bus-services-in-udaipur-transform-travel", priority: "0.64" },
  { loc: "/blog/online-bus-booking-udaipur-to-khatushyamji", priority: "0.64" },
  { loc: "/blog/delhi-to-udaipur-bus", priority: "0.64" },
  { loc: "/blog/udaipur-to-delhi-bus-online-book/", priority: "0.64" },
  { loc: "/blog/best-group-tour-services-by-rishabh-travels/", priority: "0.64" },
  { loc: "/blog/udaipur-to-salasar-bus/", priority: "0.64" },
];
